### ISSUE TITLE
Version 0.1.6 not available on Hex

### ISSUE THREAD

**Issue by valeth** [OldhamMade/phoenix_sass#6]
The latest version (0.1.6) is not published on the Hex package registry.

It appears that the mix task described in the readme was added in this version, so it won't work as expected when adding the dependency like shown in the example.

**Comment by OldhamMade** [comment]
Thanks for raising the issue!

The automated step to publish to Hex didn't complete properly. I was hoping to have a resolution over the weekend but I've not heard anything back from the original developers of that GH Action.

I've published the latest release to Hex manually, which is [now available](https://hex.pm/packages/phoenix_sass).

If you're happy with the result, please close this issue.
